#!/bin/sh

# Remove arch prefix
TAG=`echo ${DOCKER_TAG:-latest} | sed -e 's/\(amd64|arm64v8\)-//'`

if [ "$TAG" = "latest" ]; then
    TAG="fpm"
else
    TAG="${TAG}-fpm"
fi

GD_OPT="--with-freetype --with-jpeg"
ZIP_OPT=""
if [ "$TAG" = "7.2" -o "$TAG" = "7.3" ]; then
    GD_OPT="--with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/"
    ZIP_OPT="--with-libzip"
fi

docker build --build-arg TAG="${TAG}" --build-arg GD_OPT="${GD_OPT}" --build-arg ZIP_OPT="${ZIP_OPT}" -t "${IMAGE_NAME}" -f "${DOCKERFILE_PATH}" .
