#!/bin/bash

# Remove arch prefix
TAG=`echo ${DOCKER_TAG:-latest} | sed -e 's/\(amd64|arm64v8\)-//'`

# Use manifest-tool to create the manifest, given the experimental
# "docker manifest" command isn't available yet on Docker Hub.

curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.9.0/manifest-tool-linux-amd64
chmod +x manifest-tool

./manifest-tool push from-args \
    --platforms linux/amd64,linux/arm64/v8 \
    --template ${IMAGE_NAME}:ARCHVARIANT-${TAG} \
    --target ${IMAGE_NAME}:${TAG}
